export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const POST_REQUEST = "POST_REQUEST";
export const POSTLOADING_SUCCESS = "POSTLOADING_SUCCESS";
export const POSTLOADING_FAILURE = "POSTLOADING_FAILURE";

export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

export const POSTUPLOAD_REQUEST = "POSTUPLOAD_REQUEST";
export const POSTUPLOAD_SUCCESS = "POSTUPLOAD_SUCCESS";
export const POSTUPLOAD_FAILURE = "POSTUPLOAD_FAILURE";

export const USERLOAING_REQUEST = "USERLOADING_REQUEST";
export const USERLOADING_SUCCESS = "USERLOADING_SUCCESS";
export const USERLOADING_FAILURE = "USERLOADING_FAILURE";
